networks:
  spring-boot:
    driver: bridge
    name: containerized-spring-boot

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    networks:
      - spring-boot
    ports:
      - '5432'
    restart: on-failure

  exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: exporter
    networks:
      - spring-boot
    ports:
      - '9187'
    environment:
      - DATA_SOURCE_URI=postgres:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=secret