networks:
  spring-boot:
    driver: bridge
    name: containerized-spring-boot
volumes:
  pg-data:
  grafana-storage:

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_USER=flex'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=trading'
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-boot
    ports:
      - '5433:5432'
    restart: on-failure

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://flex:secret@postgres:5432/trading?sslmode=disable
    networks:
      - spring-boot
    ports:
      - '9187:9187'
    depends_on:
      - postgres

  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - spring-boot
    ports:
      - '9093:9093'
      - '9094:9094'
    restart: on-failure

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - spring-boot
    ports:
      - '8083:8080'
    depends_on:
      - kafka
    restart: on-failure

  redis:
    image: bitnami/redis:8.0.3
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - spring-boot
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./scripts/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - spring-boot
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - spring-boot
    ports:
      - '3000:3000'
